apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: yeti.sip3.net
  namespace: yeti
spec:
  secretName: yeti.sip3.net
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: yeti.sip3.net
  dnsNames:
  - yeti.sip3.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - yeti.sip3.net
    - http01:
        ingress: yeti.sip3.net
      domains:
      - yeti.sip3.net
