{{- if .Values.rbacCreate }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "yeti-web.fullname" . }}-{{ .Values.rbacServiceAccount }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "yeti-web.fullname" . }}-{{ .Values.rbacServiceAccount }}-reader
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - statefulsets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "yeti-web.fullname" . }}-{{ .Values.rbacServiceAccount }}-reader-rbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "yeti-web.fullname" . }}-{{ .Values.rbacServiceAccount }}-reader
subjects:
- kind: ServiceAccount
  name: {{ template "yeti-web.fullname" . }}-{{ .Values.rbacServiceAccount }}
---
{{ end -}}