apiVersion: v1
kind: Secret
metadata:
  name: {{ template "yeti-web.fullname" . }}-secret
  labels:
{{ include "web_labels" . | indent 4}}
type: Opaque
data:
  routing.postgres_user: {{ .Values.secret.routing_user | b64enc | quote }}
  routing.postgres_password: {{ .Values.secret.routing_pass | b64enc | quote }}
  cdr.postgres_user: {{ .Values.secret.cdr_user | b64enc | quote }}
  cdr.postgres_password: {{ .Values.secret.cdr_pass | b64enc | quote }}