apiVersion: v1
kind: Service
metadata:
  name: {{ template "yeti-web.fullname" . }}
  labels:
{{ include "web_labels" . | indent 4}}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  clusterIP: None
  selector:
    app: yeti-web
    release: {{ .Release.Name }}
  ports:
  - name: data
    port: 80
  - name: api
    port: 6666
